[package]
name = "mine"
version = "0.2.0"
edition = "2021"
publish = false

[[bin]]
name = "pepper"
path = "src/main.rs"

[dependencies]
pepper = { path = "../pepper" }
pepper-plugin-lsp = { path = "../plugin-lsp" }
pepper-plugin-remedybg = { path = "../plugin-remedybg" }

